version: 2
project_name: loops-pp-cli
changelog:
  disable: true
builds:
  - id: loops-pp-cli
    main: ./cmd/loops-pp-cli
    binary: loops-pp-cli
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/mvanhorn/printing-press-library/library/marketing/loops/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: loops-pp-mcp
    main: ./cmd/loops-pp-mcp
    binary: loops-pp-mcp
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
brews:
  - name: loops-pp-cli
    repository:
      owner: cathrynlavery
      name: homebrew-tap
    homepage: "https://github.com/mvanhorn/printing-press-library"
    description: "This is the OpenAPI Spec for the [Loops API](https://loops.so/docs/api)."
    install: |
      bin.install "loops-pp-cli"
      bin.install "loops-pp-mcp"
