version: 2
project_name: googlehealth-pp-cli
changelog:
  disable: true
builds:
  - id: googlehealth-pp-cli
    main: ./cmd/googlehealth-pp-cli
    binary: googlehealth-pp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mvanhorn/printing-press-library/library/devices/googlehealth/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: googlehealth-pp-mcp
    main: ./cmd/googlehealth-pp-mcp
    binary: googlehealth-pp-mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
brews:
  - name: googlehealth-pp-cli
    repository:
      owner: coopdogggs
      name: homebrew-tap
    homepage: "https://github.com/mvanhorn/printing-press-library"
    description: "View and manage health and fitness metrics and measurement data from Fitbit, Pixel Watch"
    install: |
      bin.install "googlehealth-pp-cli"
      bin.install "googlehealth-pp-mcp"
